Contenedor/App1/urls.py
from django.urls import path
from .views import IndexView,AutorView

urlpatterns =[
    path('', IndexView),
    path('autor/<int:id>',AutorView),
   # path('autor/<int:id>', AutorView, name="AutorName"), # Indicamos que usaremos autor/ y un parametro int
]

Contenedor/Taller/urls.py
from django.contrib import admin
from django.urls import path, include
#from App1.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("App1.urls")), # Incluimos los paths que tengan otros archivos a este que es el principal
]

Contenedor/App1/models.py
from django.db import models

# Create your models here.

class AutorDb(models.Model):
    nombre = models.CharField(max_length=75, verbose_name="Nombre")
    fecha_nacimiento = models.DateField(verbose_name="Fecha Nacimiento", null=False, blank=False)
    fecha_fallecimiento = models.DateField(verbose_name="Fecha Fallecimiento", null=True,blank=True)
    nacionalidad = models.CharField(max_length=50, verbose_name="Nacionalidad")
    profesion = models.CharField(max_length=50, verbose_name="Profesion")

    class Meta:
        db_table = "Autores"
        verbose_name = "Autor"
        verbose_name_plural="Autores"

    def __str__(self) -> str:
        return self.nombre

class FraseDb(models.Model):
    cita = models.TextField(max_length=400, verbose_name="Frase")
    autor_fk = models.ForeignKey(AutorDb, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Frase o Cita"
        verbose_name_plural=  "Frases o Citas"

Contenedor/App1/views.py
from django.shortcuts import render, get_object_or_404
from .models import AutorDb
#from django.http import HttpResponse

# Create your views here.

def IndexView(request):
    objeto = AutorDb.objects.all().order_by('-id')
    return render(request, 'index.html',{'objeto':objeto})

def AutorView(request, id):
    autor = get_object_or_404(AutorDb, id=id)
    return render(request, "autor.html", {"objeto":autor})

Contenedor/App1/templates/autor.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autores</title>
    <link rel="stylesheet" href="{% static "estilos.css"%}">
</head>
<body>
    <h1>{{objeto.nombre}}</h1>

    {% for i in objeto.frasedb_set.all %}
    <ul>
        <li>{{i.cita}}</li>
    </ul>
    {% endfor %}
    
    
<script src="{% static "scripts.js" %}"></script>

</body>
</html>

Contenedor/App1/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taller</title>
    <link rel="stylesheet" href="{% static "estilos.css"%}">
</head>
<body>
    <h1>Hola Comunidad</h1>
<ul>
    {% for i in objeto %}
    <li>{{i.nombre}}</li>
    {% endfor %}
</ul>
    <script src="{% static "scripts.js" %}"></script>
</body>
</html>